import { npc_defaults } from '../../systems/initData/npcs'

export const NpcsInitState = {
  home: { x: 0, y: 0 }, //loading
  name: '',
  inventory: [],
  clearance: 0,
  clan: '',
  body: '',
  ...npc_defaults,
}
export const seedSkills = {
  constitution: 5,
  charisma: 5, // deception?
  wisdom: 5,
  intelligence: 5,
  speed: 5,
  perception: 5, // insight
  strength: 5, //carrying capacity, intimidation
  stealth: 5, // !!
}
export const seedBinaries = {
  evil_good: 0,
  passiveAggressive: 0,
  lawlessLawful: 0,
  anti_authority: 0,
  un_educated: 0,
  poor_wealthy: 0,
  mystical_logical: 0,
  noir_color: 0,
}
export const binaryLookup: { [key: string]: { [key: string]: number } } = {
  ais: {
    evil_good: 0.3,
    passiveAggressive: -0.3,
    lawlessLawful: 0.2,
    anti_authority: -0.2,
    un_educated: 0,
    poor_wealthy: -0.1,
    mystical_logical: 0,
    noir_color: 0,
  },
  church: {
    evil_good: 0,
    passiveAggressive: -0.1,
    lawlessLawful: 0.1,
    anti_authority: 0.2,
    un_educated: -0.3,
    poor_wealthy: 0.1,
    mystical_logical: -0.2,
    noir_color: 0,
  },
  contractors: {
    evil_good: 0.1,
    passiveAggressive: -0.1,
    lawlessLawful: 0.1,
    anti_authority: 0.1,
    un_educated: 0.3,
    poor_wealthy: 0.2,
    mystical_logical: 0.1,
    noir_color: 0,
  },
  corps: {
    evil_good: -0.3,
    passiveAggressive: 0.1,
    lawlessLawful: 0,
    anti_authority: -0.1,
    un_educated: 0.2,
    poor_wealthy: 0.3,
    mystical_logical: 0,
    noir_color: 0,
  },
  gang1: {
    evil_good: -0.2,
    passiveAggressive: 0.3,
    lawlessLawful: -0.2,
    anti_authority: 0.1,
    un_educated: -0.2,
    poor_wealthy: -0.1,
    mystical_logical: -0.1,
    noir_color: 0,
  },
  gang2: {
    evil_good: -0.2,
    passiveAggressive: 0,
    lawlessLawful: -0.1,
    anti_authority: -0.1,
    un_educated: -0.2,
    poor_wealthy: 0.2,
    mystical_logical: 0,
    noir_color: 0.1,
  },
  gang3: {
    evil_good: -0.1,
    passiveAggressive: 0.2,
    lawlessLawful: -0.3,
    anti_authority: 0.2,
    un_educated: -0.1,
    poor_wealthy: 0,
    mystical_logical: 0,
    noir_color: 0,
  },
  gang4: {
    evil_good: 0.1,
    passiveAggressive: 0.1,
    lawlessLawful: -0.1,
    anti_authority: -0.2,
    un_educated: 0.2,
    poor_wealthy: -0.2,
    mystical_logical: 0,
    noir_color: 0,
  },
  labor: {
    evil_good: 0.2,
    passiveAggressive: -0.2,
    lawlessLawful: 0.2,
    anti_authority: -0.3,
    un_educated: -0.1,
    poor_wealthy: -0.3,
    mystical_logical: 0,
    noir_color: 0,
  },
  security: {
    evil_good: -0.1,
    passiveAggressive: 0.2,
    lawlessLawful: -0.2,
    anti_authority: 0.3,
    un_educated: -0.1,
    poor_wealthy: 0.1,
    mystical_logical: 0,
    noir_color: 0,
  },
  staff: {
    evil_good: 0.2,
    passiveAggressive: 0,
    lawlessLawful: -0.2,
    anti_authority: 0,
    un_educated: 0.1,
    poor_wealthy: -0.2,
    mystical_logical: 0,
    noir_color: 0,
  },
  visitors: {
    evil_good: 0,
    passiveAggressive: 0,
    lawlessLawful: 0,
    anti_authority: 0,
    un_educated: 0,
    poor_wealthy: 0,
    mystical_logical: 0,
    noir_color: 0,
  },
  sexworkers: {
    evil_good: 0,
    passiveAggressive: 0,
    lawlessLawful: 0,
    anti_authority: -0.1,
    un_educated: -0.1,
    poor_wealthy: -0.1,
    mystical_logical: 0,
    noir_color: -0.1,
  },
  doctors: {
    evil_good: 0,
    passiveAggressive: 0,
    lawlessLawful: 0.1,
    anti_authority: 0,
    un_educated: 0.1,
    poor_wealthy: 0.1,
    mystical_logical: 0.2,
    noir_color: 0,
  },
  maintenance: {
    evil_good: 0,
    passiveAggressive: -0.1,
    lawlessLawful: 0.1,
    anti_authority: 0.1,
    un_educated: -0.1,
    poor_wealthy: -0.1,
    mystical_logical: 0.1,
    noir_color: 0,
  },
  custodians: {
    evil_good: 0.1,
    passiveAggressive: 0.1,
    lawlessLawful: -0.1,
    anti_authority: -0.1,
    un_educated: -0.2,
    poor_wealthy: -0.2,
    mystical_logical: -0.1,
    noir_color: 0,
  },
  mailroom: {
    evil_good: -0.1,
    passiveAggressive: 0.2,
    lawlessLawful: -0.2,
    anti_authority: 0.1,
    un_educated: 0,
    poor_wealthy: -0.1,
    mystical_logical: 0,
    noir_color: 0,
  },
}
