import { NpcDefaults } from '../../../types/state'
const npc_defaults: NpcDefaults = {
  convos: 0,
  actions: ['talk', 'give', 'trade', 'pockets'],
  ai_path: '',
  matrix: { x: 0, y: 0 },
  attitudes: {},
  skills: {},
  binaries: {},
  turns_since_encounter: 0,
  turns_since_convo: 99,
  love: 0,
  hp: 5,
  cooldown: 0,
  effects: [],
  currentroom: '',
  exitroom: '',
  currentstation: '',
  race: '',
}
export const NpcsInitState = {
  custodian01: {
    home: { x: 3, y: 1 }, //loading
    labelname: 'custodian01',
    inventory: ['tomato', 'banana'],
    clearence: 1,
    clan: 'custodians',
    body: 'custodian01body',
    ...npc_defaults,
  },
  custodian02: {
    home: { x: 1, y: 1 }, //warehouse
    labelname: 'custodian02',
    inventory: ['mushroom03', 'vial01'],
    clearence: 1,
    clan: 'custodians',
    body: 'custodian02body',
    ...npc_defaults,
  },
  maintenance01: {
    home: { x: 4, y: 1 }, //loading
    labelname: 'maintenance01',
    inventory: ['tomato', 'banana'],
    clearence: 1,
    clan: 'maintenance',
    body: 'maintenance01body',
    ...npc_defaults,
  },
  maintenance02: {
    home: { x: 2, y: 3 }, //warehouse
    labelname: 'maintenance02',
    inventory: ['mushroom03', 'vial01'],
    clearence: 1,
    clan: 'maintenance',
    body: 'maintenance02body',
    ...npc_defaults,
  },
  labor01: {
    home: { x: 0, y: 2 }, //loading
    labelname: 'labor01',
    inventory: ['tomato', 'banana'],
    clearence: 1,
    clan: 'labor',
    body: 'labor01body',
    ...npc_defaults,
  },
  labor02: {
    home: { x: 1, y: 1 }, //warehouse
    labelname: 'labor02',
    inventory: ['mushroom03', 'vial01'],
    clearence: 1,
    clan: 'labor',
    body: 'labor02body',
    ...npc_defaults,
  },
  labor03: {
    home: { x: 4, y: 1 }, //maintenance
    labelname: 'labor03',
    inventory: ['vial02'],
    clearence: 1,
    clan: 'labor',
    body: 'labor03body',
    ...npc_defaults,
  },
  labor04: {
    home: { x: 0, y: 5 },
    labelname: 'labor04',
    inventory: ['mushroom02'],
    clearence: 1,
    clan: 'labor',
    body: 'labor04body',
    ...npc_defaults,
  },
  labor05: {
    home: { x: 2, y: 2 }, //maintenance
    labelname: 'labor05',
    inventory: ['vial02'],
    clearence: 1,
    clan: 'labor',
    body: 'labor03body',
    ...npc_defaults,
  },
  labor06: {
    home: { x: 2, y: 0 },
    labelname: 'labor06',
    inventory: ['mushroom02'],
    clearence: 1,
    clan: 'labor',
    body: 'labor04body',
    ...npc_defaults,
  },
  doc03: {
    home: { x: 1, y: 5 },
    labelname: 'doc03',
    inventory: ['orange'],
    clearence: 1,
    clan: 'doctors',
    body: 'doctors01body',
    ...npc_defaults,
  },
  doc02: {
    home: { x: 0, y: 4 },
    labelname: 'doc02',
    inventory: ['orange'],
    clearence: 1,
    clan: 'doctors',
    body: 'doctors01body',
    ...npc_defaults,
  },
  doc01: {
    home: { x: 4, y: 4 },
    labelname: 'doc01',
    inventory: ['orange', 'berry01'],
    clearence: 1,
    clan: 'doctors',
    body: 'doctors02body',
    ...npc_defaults,
  },
  contractor03: {
    home: { x: 3, y: 1 },
    labelname: 'contractor03',
    inventory: ['steak01'],
    clearence: 0,
    clan: 'contractors',
    body: 'contractors01body',
    ...npc_defaults,
  },
  contractor02: {
    home: { x: 2, y: 2 },
    labelname: 'contractor02',
    inventory: ['steak01'],
    clearence: 0,
    clan: 'contractors',
    body: 'contractors01body',
    ...npc_defaults,
  },
  contractor01: {
    home: { x: 2, y: 4 }, //admin1
    labelname: 'contractor01',
    inventory: ['earrings', 'mushroom03'],
    clearence: 0,
    clan: 'contractors',
    body: 'contractors02body',
    ...npc_defaults,
  },
  visitor03: {
    home: { x: 4, y: 4 }, //grounds
    labelname: 'visitor03',
    inventory: ['mushroom02', 'tomato'],
    clearence: 0,
    clan: 'visitors',
    body: 'visitors01body',
    ...npc_defaults,
  },
  visitor02: {
    home: { x: 0, y: 4 }, //grounds
    labelname: 'visitor02',
    inventory: ['mushroom02', 'tomato'],
    clearence: 0,
    clan: 'visitors',
    body: 'visitors01body',
    ...npc_defaults,
  },
  visitor01: {
    home: { x: 2, y: 3 }, //lobby
    labelname: 'visitor01',
    inventory: ['leaf02', 'drumstick01'],
    clearence: 0,
    clan: 'visitors',
    body: 'visitors02body',
    ...npc_defaults,
  },
  sexworker01: {
    home: { x: 4, y: 3 }, //pubgrill
    labelname: 'sexworker01',
    inventory: ['magicb2', 'shrimp01'],
    clearence: 1,
    clan: 'sexworkers',
    body: 'sexworkers01body',
    ...npc_defaults,
  },
  sexworker02: {
    home: { x: 4, y: 2 }, //inn
    labelname: 'sexworker02',
    inventory: ['leaf01', 'cheese'],
    clearence: 0,
    clan: 'sexworkers',
    body: 'sexworkers02body',
    ...npc_defaults,
  },
  sexworker03: {
    home: { x: 3, y: 3 }, //inn
    labelname: 'sexworker03',
    inventory: ['leaf01', 'cheese'],
    clearence: 0,
    clan: 'sexworkers',
    body: 'sexworkers02body',
    ...npc_defaults,
  },
  church01: {
    home: { x: 3, y: 2 }, //chapel
    labelname: 'church01',
    inventory: ['mirror', 'potion'],
    clearence: 1,
    clan: 'church',
    body: 'church02body',
    ...npc_defaults,
  },
  church02: {
    home: { x: 4, y: 4 }, //store
    labelname: 'church02',
    inventory: ['string', 'mushroom01'],
    clearence: 0,
    clan: 'church',
    body: 'church01body',
    ...npc_defaults,
  },
  church03: {
    home: { x: 2, y: 1 }, //store
    labelname: 'church03',
    inventory: ['string', 'mushroom01'],
    clearence: 0,
    clan: 'church',
    body: 'church01body',
    ...npc_defaults,
  },
  eve: {
    home: { x: 1, y: 4 }, //reception
    labelname: 'eve',
    inventory: ['bronze', 'glove01'],
    clearence: 1,
    clan: 'staff',
    body: 'staff01body',
    ...npc_defaults,
  },
  tyler: {
    home: { x: 4, y: 2 }, //inn1
    labelname: 'tyler',
    inventory: ['banana', 'cape'],
    clearence: 1,
    clan: 'staff',
    body: 'staff02body',
    ...npc_defaults,
  },
  frank: {
    home: { x: 4, y: 5 }, //dorm
    labelname: 'frank',
    inventory: ['envelope', 'vial01'],
    clearence: 1,
    clan: 'staff',
    body: 'staff03body',
    ...npc_defaults,
  },
  staff04: {
    home: { x: 4, y: 4 }, //store
    labelname: 'staff04',
    inventory: ['fish01', 'gold'],
    clearence: 1,
    clan: 'staff',
    body: 'staff04body',
    ...npc_defaults,
  },
  staff05: {
    home: { x: 2, y: 0 }, //alley3
    labelname: 'staff05',
    inventory: ['steak02', 'fish02'],
    clearence: 1,
    clan: 'staff',
    body: 'staff05body',
    ...npc_defaults,
  },
  staff06: {
    home: { x: 4, y: 5 }, //store
    labelname: 'staff06',
    inventory: ['fish01', 'gold'],
    clearence: 1,
    clan: 'staff',
    body: 'staff04body',
    ...npc_defaults,
  },
  staff07: {
    home: { x: 1, y: 0 }, //alley3
    labelname: 'staff07',
    inventory: ['steak02', 'fish02'],
    clearence: 1,
    clan: 'staff',
    body: 'staff05body',
    ...npc_defaults,
  },
  bruiser: {
    home: { x: 4, y: 1 }, //maint
    labelname: 'bruiser',
    inventory: ['egg01', 'mallot'],
    clearence: 1,
    clan: 'gang1',
    body: 'gang101body',
    ...npc_defaults,
  },
  lou: {
    home: { x: 1, y: 0 }, //alley2
    labelname: 'lou',
    inventory: ['avacado', 'shrimp02'],
    clearence: 1,
    clan: 'gang1',
    body: 'gang102body',
    ...npc_defaults,
  },
  gang103: {
    home: { x: 2, y: 1 }, //alley2
    labelname: 'gang103',
    inventory: ['avacado', 'shrimp02'],
    clearence: 1,
    clan: 'gang1',
    body: 'gang102body',
    ...npc_defaults,
  },
  spike: {
    home: { x: 4, y: 3 },
    labelname: 'spike',
    inventory: ['rose', 'berry02'],
    clearence: 1,
    clan: 'gang2',
    body: 'gang201body',
    ...npc_defaults,
  },
  curly: {
    home: { x: 4, y: 5 },
    labelname: 'curly',
    inventory: ['berry02', 'avacado'],
    clearence: 1,
    clan: 'gang2',
    body: 'gang202body',
    ...npc_defaults,
  },
  gang203: {
    home: { x: 4, y: 1 }, //alley2
    labelname: 'gang203',
    inventory: ['avacado', 'shrimp02'],
    clearence: 1,
    clan: 'gang1',
    body: 'gang102body',
    ...npc_defaults,
  },
  gang302: {
    home: { x: 0, y: 0 },
    labelname: 'gang302',
    inventory: ['shrimp02', 'egg01'],
    clearence: 1,
    clan: 'gang3',
    body: 'gang301body',
    ...npc_defaults,
  },
  gang301: {
    home: { x: 3, y: 3 },
    labelname: 'gang301',
    inventory: ['magicc5', 'steak02'],
    clearence: 1,
    clan: 'gang3',
    body: 'gang302body',
    ...npc_defaults,
  },
  gang303: {
    home: { x: 2, y: 3 },
    labelname: 'gang303',
    inventory: ['magicc5', 'steak02'],
    clearence: 1,
    clan: 'gang3',
    body: 'gang302body',
    ...npc_defaults,
  },
  gang402: {
    home: { x: 3, y: 4 },
    labelname: 'gang402',
    inventory: ['fish02', 'sunhat'],
    clearence: 1,
    clan: 'gang4',
    body: 'gang401body',
    ...npc_defaults,
  },
  gang401: {
    home: { x: 4, y: 5 },
    labelname: 'gang401',
    inventory: ['eyeball02', 'fish01'],
    clearence: 1,
    clan: 'gang4',
    body: 'gang402body',
    ...npc_defaults,
  },
  gang403: {
    home: { x: 3, y: 4 },
    labelname: 'gang403',
    inventory: ['magicc5', 'steak02'],
    clearence: 1,
    clan: 'gang3',
    body: 'gang302body',
    ...npc_defaults,
  },
  corps02: {
    home: { x: 2, y: 4 }, //admin1
    labelname: 'corps02',
    inventory: ['magicb3', 'vial01'],
    clearence: 1,
    clan: 'corps',
    body: 'corps01body',
    ...npc_defaults,
  },
  corps01: {
    home: { x: 3, y: 5 }, //admin2
    labelname: 'corps01',
    inventory: ['sack', 'banana'],
    clearence: 1,
    clan: 'corps',
    body: 'corps02body',
    ...npc_defaults,
  },
  corps03: {
    home: { x: 1, y: 5 }, //vip
    labelname: 'corps03',
    inventory: ['magica4', 'mushroom02'],
    clearence: 1,
    clan: 'corps',
    body: 'corps03body',
    ...npc_defaults,
  },
  security001: {
    home: { x: 1, y: 3 }, //customs
    labelname: 'security001',
    inventory: ['potion', 'orange'],
    clearence: 1,
    clan: 'security',
    body: 'security01body',
    ...npc_defaults,
  },
  security002: {
    //matrix: { x: 3, y: 6 },
    home: { x: 0, y: 3 }, //baggage
    labelname: 'security002',
    inventory: ['ring', 'mushroom03'],
    clearence: 1,
    clan: 'security',
    body: 'security02body',
    ...npc_defaults,
  },
  security003: {
    home: { x: 4, y: 4 }, //store
    labelname: 'security003',
    inventory: ['drumstick01', 'tomato'],
    clearence: 2,
    clan: 'security',
    body: 'security03body',
    ...npc_defaults,
  },
  security004: {
    home: { x: 4, y: 1 }, //maint
    labelname: 'security004',
    inventory: ['coffeemug', 'orange'],
    clearence: 2,
    clan: 'security',
    body: 'security04body',
    ...npc_defaults,
  },
  security005: {
    home: { x: 4, y: 1 }, //maint
    labelname: 'security005',
    inventory: ['coffeemug', 'orange'],
    clearence: 2,
    clan: 'security',
    body: 'security04body',
    ...npc_defaults,
  },
}
