import { Npc, NpcDefaults } from '../../../types/state'
export const npc_defaults: NpcDefaults = {
  convos: 0,
  actions: ['talk', 'give', 'trade', 'pockets'],
  aiPath: '',
  matrix: { x: 0, y: 0 },
  traits: { opinion: {}, skills: {}, binaries: {} },
  turnPriority: 0,
  sincePlayerConvo: 99,
  love: 0,
  hp: 5,
  cooldown: 0,
  effects: [],
  currRoom: '',
  exitRoom: '',
  currStation: '',
  race: '',
}
export const NpcsInitState: { [key: string]: Npc } = {
  mailroom01: {
    home: { x: 3, y: 1 }, //loading
    name: 'mailroom01',
    inventory: ['tomato', 'banana'],
    clearance: 3,
    clan: 'mailroom',
    body: 'mailroom01body',
    ...npc_defaults,
  },
  mailroom02: {
    home: { x: 1, y: 1 }, //warehouse
    name: 'mailroom02',
    inventory: ['mushroom02', 'leaf02'],
    clearance: 2,
    clan: 'mailroom',
    body: 'mailroom02body',
    ...npc_defaults,
  },
  mailroom03: {
    home: { x: 2, y: 4 }, //warehouse
    name: 'mailroom03',
    inventory: ['magicb3', 'shrimp02'],
    clearance: 3,
    clan: 'mailroom',
    body: 'mailroom01body',
    ...npc_defaults,
  },
  custodian01: {
    home: { x: 3, y: 1 }, //loading
    name: 'custodian01',
    inventory: ['tomato', 'banana'],
    clearance: 3,
    clan: 'custodians',
    body: 'custodian01body',
    ...npc_defaults,
  },
  custodian02: {
    home: { x: 1, y: 1 }, //warehouse
    name: 'custodian02',
    inventory: ['magica4', 'drumstick01'],
    clearance: 2,
    clan: 'custodians',
    body: 'custodian02body',
    ...npc_defaults,
  },
  maintenance01: {
    home: { x: 4, y: 1 }, //loading
    name: 'maintenance01',
    inventory: ['tomato', 'banana'],
    clearance: 3,
    clan: 'maintenance',
    body: 'maintenance01body',
    ...npc_defaults,
  },
  maintenance02: {
    home: { x: 2, y: 3 }, //warehouse
    name: 'maintenance02',
    inventory: ['string', 'mirror'],
    clearance: 2,
    clan: 'maintenance',
    body: 'maintenance02body',
    ...npc_defaults,
  },
  labor01: {
    home: { x: 0, y: 2 }, //loading
    name: 'labor01',
    inventory: ['tomato', 'banana'],
    clearance: 2,
    clan: 'labor',
    body: 'labor01body',
    ...npc_defaults,
  },
  labor02: {
    home: { x: 1, y: 1 }, //warehouse
    name: 'labor02',
    inventory: ['feather01', 'vial01'],
    clearance: 2,
    clan: 'labor',
    body: 'labor02body',
    ...npc_defaults,
  },
  labor03: {
    home: { x: 4, y: 1 }, //maintenance
    name: 'labor03',
    inventory: ['vial02'],
    clearance: 2,
    clan: 'labor',
    body: 'labor03body',
    ...npc_defaults,
  },
  labor04: {
    home: { x: 0, y: 5 },
    name: 'labor04',
    inventory: ['mushroom02'],
    clearance: 2,
    clan: 'labor',
    body: 'labor04body',
    ...npc_defaults,
  },
  labor05: {
    home: { x: 2, y: 2 }, //maintenance
    name: 'labor05',
    inventory: ['vial02'],
    clearance: 3,
    clan: 'labor',
    body: 'labor03body',
    ...npc_defaults,
  },
  labor06: {
    home: { x: 2, y: 0 },
    name: 'labor06',
    inventory: ['mushroom02'],
    clearance: 1,
    clan: 'labor',
    body: 'labor04body',
    ...npc_defaults,
  },
  labor07: {
    home: { x: 2, y: 1 },
    name: 'labor07',
    inventory: ['mushroom01'],
    clearance: 1,
    clan: 'labor',
    body: 'labor01body',
    ...npc_defaults,
  },
  doc03: {
    home: { x: 1, y: 5 },
    name: 'doc03',
    inventory: ['orange'],
    clearance: 3,
    clan: 'doctors',
    body: 'doctors01body',
    ...npc_defaults,
  },
  doc02: {
    home: { x: 0, y: 4 },
    name: 'doc02',
    inventory: ['orange'],
    clearance: 3,
    clan: 'doctors',
    body: 'doctors01body',
    ...npc_defaults,
  },
  doc01: {
    home: { x: 4, y: 4 },
    name: 'doc01',
    inventory: ['orange', 'berry01'],
    clearance: 3,
    clan: 'doctors',
    body: 'doctors02body',
    ...npc_defaults,
  },
  contractor04: {
    home: { x: 3, y: 2 },
    name: 'contractor04',
    inventory: ['steak01'],
    clearance: 3,
    clan: 'contractors',
    body: 'contractors02body',
    ...npc_defaults,
  },
  contractor03: {
    home: { x: 3, y: 1 },
    name: 'contractor03',
    inventory: ['steak01'],
    clearance: 3,
    clan: 'contractors',
    body: 'contractors01body',
    ...npc_defaults,
  },
  contractor02: {
    home: { x: 2, y: 2 },
    name: 'contractor02',
    inventory: ['steak01'],
    clearance: 3,
    clan: 'contractors',
    body: 'contractors01body',
    ...npc_defaults,
  },
  contractor01: {
    home: { x: 2, y: 4 }, //admin1
    name: 'contractor01',
    inventory: ['earrings', 'mushroom03'],
    clearance: 2,
    clan: 'contractors',
    body: 'contractors02body',
    ...npc_defaults,
  },
  visitor04: {
    home: { x: 5, y: 4 }, //grounds
    name: 'visitor04',
    inventory: ['steak01', 'tomato'],
    clearance: 2,
    clan: 'visitors',
    body: 'visitors02body',
    ...npc_defaults,
  },
  visitor03: {
    home: { x: 4, y: 4 }, //grounds
    name: 'visitor03',
    inventory: ['mushroom02', 'tomato'],
    clearance: 2,
    clan: 'visitors',
    body: 'visitors01body',
    ...npc_defaults,
  },
  visitor02: {
    home: { x: 0, y: 4 }, //grounds
    name: 'visitor02',
    inventory: ['mushroom02', 'tomato'],
    clearance: 3,
    clan: 'visitors',
    body: 'visitors01body',
    ...npc_defaults,
  },
  visitor01: {
    home: { x: 2, y: 3 }, //lobby
    name: 'visitor01',
    inventory: ['leaf02', 'drumstick01'],
    clearance: 1,
    clan: 'visitors',
    body: 'visitors02body',
    ...npc_defaults,
  },
  sexworker01: {
    home: { x: 4, y: 3 }, //pubgrill
    name: 'sexworker01',
    inventory: ['magicb2', 'shrimp01'],
    clearance: 1,
    clan: 'sexworkers',
    body: 'sexworkers01body',
    ...npc_defaults,
  },
  sexworker02: {
    home: { x: 4, y: 2 }, //inn
    name: 'sexworker02',
    inventory: ['leaf01', 'cheese'],
    clearance: 2,
    clan: 'sexworkers',
    body: 'sexworkers02body',
    ...npc_defaults,
  },
  sexworker03: {
    home: { x: 3, y: 3 }, //inn
    name: 'sexworker03',
    inventory: ['leaf01', 'cheese'],
    clearance: 3,
    clan: 'sexworkers',
    body: 'sexworkers02body',
    ...npc_defaults,
  },
  church01: {
    home: { x: 3, y: 2 }, //chapel
    name: 'church01',
    inventory: ['mirror', 'potion'],
    clearance: 1,
    clan: 'church',
    body: 'church02body',
    ...npc_defaults,
  },
  church02: {
    home: { x: 4, y: 4 }, //store
    name: 'church02',
    inventory: ['string', 'mushroom01'],
    clearance: 2,
    clan: 'church',
    body: 'church01body',
    ...npc_defaults,
  },
  church03: {
    home: { x: 2, y: 1 }, //store
    name: 'church03',
    inventory: ['string', 'mushroom01'],
    clearance: 3,
    clan: 'church',
    body: 'church01body',
    ...npc_defaults,
  },
  eve: {
    home: { x: 1, y: 4 }, //reception
    name: 'eve',
    inventory: ['bronze', 'glove01'],
    clearance: 2,
    clan: 'staff',
    body: 'staff01body',
    ...npc_defaults,
  },
  tyler: {
    home: { x: 4, y: 2 }, //inn1
    name: 'tyler',
    inventory: ['banana', 'cape'],
    clearance: 1,
    clan: 'staff',
    body: 'staff02body',
    ...npc_defaults,
  },
  frank: {
    home: { x: 4, y: 5 }, //dorm
    name: 'frank',
    inventory: ['envelope', 'vial01'],
    clearance: 3,
    clan: 'staff',
    body: 'staff03body',
    ...npc_defaults,
  },
  staff04: {
    home: { x: 4, y: 4 }, //store
    name: 'staff04',
    inventory: ['fish01', 'gold'],
    clearance: 2,
    clan: 'staff',
    body: 'staff04body',
    ...npc_defaults,
  },
  staff05: {
    home: { x: 2, y: 0 }, //alley3
    name: 'staff05',
    inventory: ['steak02', 'fish02'],
    clearance: 2,
    clan: 'staff',
    body: 'staff05body',
    ...npc_defaults,
  },
  staff06: {
    home: { x: 4, y: 5 }, //store
    name: 'staff06',
    inventory: ['fish01', 'gold'],
    clearance: 3,
    clan: 'staff',
    body: 'staff04body',
    ...npc_defaults,
  },
  staff07: {
    home: { x: 1, y: 0 }, //alley3
    name: 'staff07',
    inventory: ['steak02', 'fish02'],
    clearance: 1,
    clan: 'staff',
    body: 'staff05body',
    ...npc_defaults,
  },
  staff08: {
    home: { x: 2, y: 1 }, //alley3
    name: 'staff08',
    inventory: ['mallot', 'fish02'],
    clearance: 1,
    clan: 'staff',
    body: 'staff04body',
    ...npc_defaults,
  },
  bruiser: {
    home: { x: 4, y: 1 }, //maint
    name: 'bruiser',
    inventory: ['egg01', 'mallot'],
    clearance: 1,
    clan: 'gang1',
    body: 'gang101body',
    ...npc_defaults,
  },
  lou: {
    home: { x: 1, y: 0 }, //alley2
    name: 'lou',
    inventory: ['avacado', 'shrimp02'],
    clearance: 2,
    clan: 'gang1',
    body: 'gang102body',
    ...npc_defaults,
  },
  gang103: {
    home: { x: 2, y: 1 }, //alley2
    name: 'gang103',
    inventory: ['avacado', 'shrimp02'],
    clearance: 3,
    clan: 'gang1',
    body: 'gang102body',
    ...npc_defaults,
  },
  spike: {
    home: { x: 4, y: 3 },
    name: 'spike',
    inventory: ['rose', 'berry02'],
    clearance: 3,
    clan: 'gang2',
    body: 'gang201body',
    ...npc_defaults,
  },
  curly: {
    home: { x: 4, y: 5 },
    name: 'curly',
    inventory: ['berry02', 'avacado'],
    clearance: 1,
    clan: 'gang2',
    body: 'gang202body',
    ...npc_defaults,
  },
  gang203: {
    home: { x: 4, y: 1 }, //alley2
    name: 'gang203',
    inventory: ['avacado', 'shrimp02'],
    clearance: 2,
    clan: 'gang1',
    body: 'gang102body',
    ...npc_defaults,
  },
  gang302: {
    home: { x: 0, y: 0 },
    name: 'gang302',
    inventory: ['shrimp02', 'egg01'],
    clearance: 3,
    clan: 'gang3',
    body: 'gang301body',
    ...npc_defaults,
  },
  gang301: {
    home: { x: 3, y: 3 },
    name: 'gang301',
    inventory: ['magicc5', 'steak02'],
    clearance: 2,
    clan: 'gang3',
    body: 'gang302body',
    ...npc_defaults,
  },
  gang303: {
    home: { x: 2, y: 3 },
    name: 'gang303',
    inventory: ['magicc5', 'steak02'],
    clearance: 1,
    clan: 'gang3',
    body: 'gang302body',
    ...npc_defaults,
  },
  gang402: {
    home: { x: 3, y: 4 },
    name: 'gang402',
    inventory: ['fish02', 'sunhat'],
    clearance: 2,
    clan: 'gang4',
    body: 'gang401body',
    ...npc_defaults,
  },
  gang401: {
    home: { x: 4, y: 5 },
    name: 'gang401',
    inventory: ['eyeball02', 'fish01'],
    clearance: 1,
    clan: 'gang4',
    body: 'gang402body',
    ...npc_defaults,
  },
  gang403: {
    home: { x: 3, y: 4 },
    name: 'gang403',
    inventory: ['magicc5', 'steak02'],
    clearance: 3,
    clan: 'gang3',
    body: 'gang302body',
    ...npc_defaults,
  },
  corps02: {
    home: { x: 2, y: 4 }, //admin1
    name: 'corps02',
    inventory: ['magicb3', 'vial01'],
    clearance: 2,
    clan: 'corps',
    body: 'corps01body',
    ...npc_defaults,
  },
  corps01: {
    home: { x: 3, y: 5 }, //admin2
    name: 'corps01',
    inventory: ['sack', 'banana'],
    clearance: 3,
    clan: 'corps',
    body: 'corps02body',
    ...npc_defaults,
  },
  corps03: {
    home: { x: 1, y: 5 }, //vip
    name: 'corps03',
    inventory: ['magica4', 'mushroom02'],
    clearance: 3,
    clan: 'corps',
    body: 'corps03body',
    ...npc_defaults,
  },
  corps04: {
    home: { x: 2, y: 5 }, //vip
    name: 'corps04',
    inventory: ['magica4', 'potion'],
    clearance: 3,
    clan: 'corps',
    body: 'corps03body',
    ...npc_defaults,
  },
  security001: {
    home: { x: 1, y: 3 }, //customs
    name: 'security001',
    inventory: ['potion', 'orange'],
    clearance: 3,
    clan: 'security',
    body: 'security01body',
    ...npc_defaults,
  },
  security002: {
    //matrix: { x: 3, y: 6 },
    home: { x: 0, y: 3 }, //baggage
    name: 'security002',
    inventory: ['ring', 'mushroom03'],
    clearance: 3,
    clan: 'security',
    body: 'security02body',
    ...npc_defaults,
  },
  security003: {
    home: { x: 4, y: 4 }, //store
    name: 'security003',
    inventory: ['drumstick01', 'tomato'],
    clearance: 3,
    clan: 'security',
    body: 'security03body',
    ...npc_defaults,
  },
  security004: {
    home: { x: 4, y: 1 }, //maint
    name: 'security004',
    inventory: ['coffeemug', 'orange'],
    clearance: 3,
    clan: 'security',
    body: 'security04body',
    ...npc_defaults,
  },
  security005: {
    home: { x: 4, y: 1 }, //maint
    name: 'security005',
    inventory: ['coffeemug', 'orange'],
    clearance: 2,
    clan: 'security',
    body: 'security04body',
    ...npc_defaults,
  },
}

export const seedSkills = {
  constitution: 5,
  charisma: 5, // deception?
  wisdom: 5,
  intelligence: 5,
  speed: 5,
  perception: 5, // insight
  strength: 5, //carrying capacity, intimidation
  stealth: 5, // !!
}
export const seedBinaries = {
  evil_good: 0,
  passiveAggressive: 0,
  lawlessLawful: 0,
  anti_authority: 0,
  un_educated: 0,
  poor_wealthy: 0,
  mystical_logical: 0,
  noir_color: 0,
}
export const binaryLookup: { [key: string]: { [key: string]: number } } = {
  ais: {
    evil_good: 0.3,
    passiveAggressive: -0.3,
    lawlessLawful: 0.2,
    anti_authority: -0.2,
    un_educated: 0,
    poor_wealthy: -0.1,
    mystical_logical: 0,
    noir_color: 0,
  },
  church: {
    evil_good: 0,
    passiveAggressive: -0.1,
    lawlessLawful: 0.1,
    anti_authority: 0.2,
    un_educated: -0.3,
    poor_wealthy: 0.1,
    mystical_logical: -0.2,
    noir_color: 0,
  },
  contractors: {
    evil_good: 0.1,
    passiveAggressive: -0.1,
    lawlessLawful: 0.1,
    anti_authority: 0.1,
    un_educated: 0.3,
    poor_wealthy: 0.2,
    mystical_logical: 0.1,
    noir_color: 0,
  },
  corps: {
    evil_good: -0.3,
    passiveAggressive: 0.1,
    lawlessLawful: 0,
    anti_authority: -0.1,
    un_educated: 0.2,
    poor_wealthy: 0.3,
    mystical_logical: 0,
    noir_color: 0,
  },
  gang1: {
    evil_good: -0.2,
    passiveAggressive: 0.3,
    lawlessLawful: -0.2,
    anti_authority: 0.1,
    un_educated: -0.2,
    poor_wealthy: -0.1,
    mystical_logical: -0.1,
    noir_color: 0,
  },
  gang2: {
    evil_good: -0.2,
    passiveAggressive: 0,
    lawlessLawful: -0.1,
    anti_authority: -0.1,
    un_educated: -0.2,
    poor_wealthy: 0.2,
    mystical_logical: 0,
    noir_color: 0.1,
  },
  gang3: {
    evil_good: -0.1,
    passiveAggressive: 0.2,
    lawlessLawful: -0.3,
    anti_authority: 0.2,
    un_educated: -0.1,
    poor_wealthy: 0,
    mystical_logical: 0,
    noir_color: 0,
  },
  gang4: {
    evil_good: 0.1,
    passiveAggressive: 0.1,
    lawlessLawful: -0.1,
    anti_authority: -0.2,
    un_educated: 0.2,
    poor_wealthy: -0.2,
    mystical_logical: 0,
    noir_color: 0,
  },
  labor: {
    evil_good: 0.2,
    passiveAggressive: -0.2,
    lawlessLawful: 0.2,
    anti_authority: -0.3,
    un_educated: -0.1,
    poor_wealthy: -0.3,
    mystical_logical: 0,
    noir_color: 0,
  },
  security: {
    evil_good: -0.1,
    passiveAggressive: 0.2,
    lawlessLawful: -0.2,
    anti_authority: 0.3,
    un_educated: -0.1,
    poor_wealthy: 0.1,
    mystical_logical: 0,
    noir_color: 0,
  },
  staff: {
    evil_good: 0.2,
    passiveAggressive: 0,
    lawlessLawful: -0.2,
    anti_authority: 0,
    un_educated: 0.1,
    poor_wealthy: -0.2,
    mystical_logical: 0,
    noir_color: 0,
  },
  visitors: {
    evil_good: 0,
    passiveAggressive: 0,
    lawlessLawful: 0,
    anti_authority: 0,
    un_educated: 0,
    poor_wealthy: 0,
    mystical_logical: 0,
    noir_color: 0,
  },
  sexworkers: {
    evil_good: 0,
    passiveAggressive: 0,
    lawlessLawful: 0,
    anti_authority: -0.1,
    un_educated: -0.1,
    poor_wealthy: -0.1,
    mystical_logical: 0,
    noir_color: -0.1,
  },
  doctors: {
    evil_good: 0,
    passiveAggressive: 0,
    lawlessLawful: 0.1,
    anti_authority: 0,
    un_educated: 0.1,
    poor_wealthy: 0.1,
    mystical_logical: 0.2,
    noir_color: 0,
  },
  maintenance: {
    evil_good: 0,
    passiveAggressive: -0.1,
    lawlessLawful: 0.1,
    anti_authority: 0.1,
    un_educated: -0.1,
    poor_wealthy: -0.1,
    mystical_logical: 0.1,
    noir_color: 0,
  },
  custodians: {
    evil_good: 0.1,
    passiveAggressive: 0.1,
    lawlessLawful: -0.1,
    anti_authority: -0.1,
    un_educated: -0.2,
    poor_wealthy: -0.2,
    mystical_logical: -0.1,
    noir_color: 0,
  },
  mailroom: {
    evil_good: -0.1,
    passiveAggressive: 0.2,
    lawlessLawful: -0.2,
    anti_authority: 0.1,
    un_educated: 0,
    poor_wealthy: -0.1,
    mystical_logical: 0,
    noir_color: 0,
  },
}
