import { Room } from '../../../types/state'
export const RoomsInitLayout = [
  ['alley1', 'alley2', 'alley3', 'alley4', 'alley5'],
  ['unloading', 'warehouse', 'commonsext', 'storage', 'maintenance'],
  // put a hallway here testjpf!!!
  ['loading', 'lockers', 'commonsint', 'chapel', 'inn1'],
  ['baggage', 'customs', 'lobby', 'recroom', 'pubgrill'],
  ['grounds', 'reception', 'admin1', 'gym', 'store'],
  ['entrance', 'viplobby', 'security', 'infirmary', 'dorms'],
]
export const RoomsInitState: { [key: string]: Room } = {
  roomexample: {
    matrix: { x: 2, y: 5 },
    name: 'roomexample',
    clearance: 3,
    props: [],
    actors: {},
    stationKeys: [],
    focus: false,
    onScreen: false,
    moments: [],
  },
}
export const RoomsInitPriority = [
  'grounds',
  'reception',
  'customs',
  'baggage',
  'admin1',
  'security',
  'infirmary',
  'viplobby',
  'entrance',
  'lobby',
  'lockers',
  'commonsint',
  'gym',
  'recroom',
  'chapel',
  'loading',
  'unloading',
  'warehouse',
  'commonsext',
  'storage',
  'alley1',
  'alley2',
  'alley3',
  'store',
  'pubgrill',
  'dorms',
  'inn1',
  'maintenance',
  'alley4',
  'alley5',
]
