import { Jail } from '../../../types/state'

const securityRoom: Jail = {
  matrix: { x: 2, y: 5 },
  roomname: 'security',
  stations: { guard: '', authority: '', assistant: '' },
  prisoners: { prisoner1: '', prisoner2: '', prisoner3: '', prisoner4: '' },
  actors: {},
}
export const RoomsInitState = {
  security: { ...securityRoom },
  baggage: {
    matrix: { x: 1, y: 4 },
    roomname: 'baggage',
    stations: {
      guard: '',
      worker1: '',
      assistant: '',
      browse: '',
    },
    actors: {
      luggage_1: {
        inventory: [],
        watcher: 'browse',
        actions: ['open'],
      },
      luggage_2: {
        inventory: [],
        watcher: 'guard',
        actions: ['open'],
      },
    },
  },
  viplobby: {
    matrix: { x: 1, y: 5 },
    roomname: 'viplobby',
    stations: {
      guard: '',
      vipguest: '',
      boss: '',
      authority: '',
      host: '',
      desk: '',
      servants1: '',
    },
    actors: {},
  },
  entrance: {
    matrix: { x: 0, y: 5 },
    roomname: 'entrance',
    stations: {
      loiter2: '',
      worker1: '',
      loiter3: '',
      guest: '',
      guest2: '',
      host: '',
    },
    actors: {},
  },
  recroom: {
    matrix: { x: 3, y: 3 },
    roomname: 'recroom',
    stations: {
      lounge: '',
      loiter1: '',
      loiter2: '',
      worker2: '',
      guest: '',
      bench: '',
      browse: '',
    },
    actors: {},
  },
  chapel: {
    matrix: { x: 3, y: 2 },
    roomname: 'chapel',
    stations: {
      loiter1: '',
      loiter2: '',
      authority: '',
      loiter3: '',
      guest: '',
      loiter4: '',
    },
    actors: {},
  },
  inn1: {
    matrix: { x: 4, y: 2 },
    roomname: 'inn1',
    stations: {
      loiter3: '',
      host: '',
      tender: '',
      guest: '',
      lounge: '',
      loiter1: '',
    },
    actors: {},
  },
  pubgrill: {
    matrix: { x: 4, y: 3 },
    roomname: 'pubgrill',
    stations: {
      host: '',
      bar: '',
      table: '',
      tender: '',
      loiter3: '',
      guest: '',
    },
    actors: {},
  },
  maintenance: {
    matrix: { x: 4, y: 1 },
    roomname: 'maintenance',
    stations: { bench: '', patrol: '', browse: '', worker1: '' },
    actors: {},
  },
  lobby: {
    matrix: { x: 2, y: 3 },
    roomname: 'lobby',
    stations: {
      loiter1: '',
      loiter2: '',
      guard: '',
      loiter4: '',
      table: '',
      guest: '',
      loiter3: '',
    },
    actors: {},
  },
  storage: {
    matrix: { x: 3, y: 1 },
    roomname: 'storage',
    stations: {
      patrol: '',
      guard: '',
      assistant: '',
      browse: '',
      employee: '',
    },
    actors: {},
  },
  commonsint: {
    matrix: { x: 2, y: 2 },
    roomname: 'commonsint',
    stations: {
      loiter1: '',
      loiter2: '',
      loiter3: '',
      loiter4: '',
      lounge: '',
      guest: '',
      servants1: '',
    },
    actors: {},
  },
  commonsext: {
    matrix: { x: 2, y: 1 },
    roomname: 'commonsext',
    stations: {
      loiter1: '',
      loiter2: '',
      loiter3: '',
      patrol: '',
      table: '',
      guest: '',
      servants2: '',
    },
    actors: {},
  },
  warehouse: {
    matrix: { x: 1, y: 1 },
    roomname: 'warehouse',
    stations: { worker1: '', worker2: '', boss: '' },
    actors: {},
  },
  lockers: {
    matrix: { x: 1, y: 2 },
    roomname: 'lockers',
    stations: {
      loiter1: '',
      patrol: '',
      loiter2: '',
      table: '',
      lounge: '',
      guest: '',
      servants2: '',
    },
    actors: {},
  },
  unloading: {
    matrix: { x: 0, y: 1 },
    roomname: 'unloading',
    stations: {
      worker1: '',
      worker2: '',
      boss: '',
      servants1: '',
      gang: '',
      guard: '',
    },
    actors: {},
  },
  alley3: {
    matrix: { x: 2, y: 0 },
    roomname: 'alley3',
    stations: {
      worker1: '',
      servants1: '',
      gang: '',
      loiter2: '',
      loiter4: '',
      servants2: '',
      patrol: '',
    },
    actors: {},
  },
  alley2: {
    matrix: { x: 1, y: 0 },
    roomname: 'alley2',
    stations: {
      worker1: '',
      servants1: '',
      gang: '',
      loiter2: '',
      guard: '',
    },
    actors: {},
  },
  alley1: {
    matrix: { x: 0, y: 0 },
    roomname: 'alley1',
    stations: {
      worker1: '',
      worker2: '',
      servants1: '',
      gang: '',
      patrol: '',
    },
    actors: {},
  },
  loading: {
    matrix: { x: 0, y: 2 },
    roomname: 'loading',
    stations: { worker1: '', worker2: '', boss: '', patrol: '', gang: '' },
    actors: {},
  },
  admin1: {
    matrix: { x: 2, y: 4 },
    roomname: 'admin1',
    props: ['desks', 'locker'],
    stations: {
      monitor: '',
      patrol: '',
      guard: '',
      assistant: '',
      boss: '',
      desk: '',
    },
    actors: {
      desks: {
        inventory: [],
        actions: ['pickup', 'use'],
      },
      locker: {
        inventory: [],
        actions: ['use', 'open'],
      },
    },
  },
  customs: {
    matrix: { x: 1, y: 3 },
    roomname: 'customs',
    props: ['desks', 'locker'],
    stations: {
      desk: '',
      loiter1: '',
      guard: '',
      patrol: '',
      loiter3: '',
      loiter4: '',
      guest: '',
    },
    actors: {
      desks: {
        inventory: ['deskbook01', 'globegold'],
        actions: ['pickup', 'use'],
      },
      locker: {
        inventory: ['silver', 'mushroom01'],
        actions: ['use', 'open'],
      },
    },
  },
  reception: {
    matrix: { x: 1, y: 4 },
    roomname: 'reception',
    props: ['drawer', 'computer'],
    stations: {
      desk: '',
      patrol: '',
      guard: '',
      loiter2: '',
      loiter4: '',
      guest: '',
      guest2: '',
    },
    actors: {
      drawer: {
        inventory: ['cheese', 'shrimp01'],
        actions: ['open'],
        watcher: 'desk',
      },
      computer: {
        inventory: [],
        actions: ['use'],
        watcher: 'desk',
      },
      vase: {
        inventory: ['pillow', 'book'],
        actions: ['open'],
        watcher: 'loiter2',
      },
      vase2: {
        inventory: ['steak01', 'leaf03', 'daisy'],
        actions: ['open'],
        watcher: 'patrol',
      },
    },
  },
  grounds: {
    matrix: { x: 0, y: 4 },
    roomname: 'grounds',
    stations: {
      assistant: '',
      worker1: '',
      aid: '',
      guest: '',
      worker2: '',
      loiter1: '',
      guest2: '',
    },
    actors: {
      player_luggage: {
        inventory: ['berry01', 'feather01', 'magica1'],
        watcher: 'worker2',
        actions: ['open'],
      },
      other_luggage: {
        inventory: ['eyeball03', 'feather02', 'magicb1'],
        watcher: 'worker2',
        actions: ['open'],
      },
    },
  },
  dorms: {
    matrix: { x: 4, y: 5 },
    roomname: 'dorms',
    stations: {
      bench: '',
      servants1: '',
      servants2: '',
      assistant: '',
      loiter2: '',
      gang: '',
    },
    actors: {},
  },
  gym: {
    matrix: { x: 3, y: 4 },
    roomname: 'gym',
    stations: {
      //guest: "",
      browse: '',
      //loiter2: "",
      loiter4: '',
      bench: '',
      servants1: '',
    },
    actors: {},
  },
  store: {
    matrix: { x: 4, y: 4 },
    roomname: 'store',
    stations: {
      guest: '',
      servants1: '',
      employee: '',
      patrol: '',
      loiter3: '',
      worker1: '',
      loiter2: '',
    },
    actors: {},
  },
  infirmary: {
    matrix: { x: 3, y: 5 },
    roomname: 'infirmary',
    props: ['drawer', 'computer'],
    stations: {
      aid: '',
      loiter1: '',
      loiter2: '',
      assistant: '',
      loiter4: '',
    },
    actors: {
      drawer: {
        inventory: ['vial02'],
        actions: ['open'],
        watcher: 'assistant',
      },
      computer: {
        inventory: [],
        actions: ['use'],
        watcher: 'assistant',
      },
    },
  },
}

export const RoomsInitLayout = [
  ['alley1', 'alley2', 'alley3', null, null],
  ['unloading', 'warehouse', 'commonsext', 'storage', 'maintenance'],
  ['loading', 'lockers', 'commonsint', 'chapel', 'inn1'],
  ['baggage', 'customs', 'lobby', 'recroom', 'pubgrill'],
  ['grounds', 'reception', 'admin1', 'gym', 'store'],
  ['entrance', 'viplobby', 'security', 'infirmary', 'dorms'],
]
export const RoomsInitRoles = {
  desk: ['staff', 'security'],
  host: ['staff', 'gang1', 'gang2'],
  tender: ['staff', 'gang3', 'gang4'],
  bar: [
    'doctors',
    'corps',
    'visitors',
    'church',
    'contractors',
    'sexworkers',
    'labor',
    'security',
  ],
  table: [
    'doctors',
    'corps',
    'visitors',
    'church',
    'contractors',
    'sexworkers',
    'labor',
    'security',
  ],
  bench: ['labor', 'contractors', 'gang1', 'gang3'],
  browse: ['staff', 'labor', 'contractors', 'gang2', 'gang4', 'security'],
  monitor: ['security', 'staff', 'corps', 'doctors'],
  guard: ['security', 'gang1', 'gang3'],
  patrol: ['security', 'gang2', 'gang4', 'corps', 'staff'],
  loiter1: [
    'sexworkers',
    'visitors',
    'church',
    'corps',
    'gang1',
    'gang2',
    'contractors',
  ],
  loiter2: [
    'sexworkers',
    'staff',
    'church',
    'gang3',
    'gang4',
    'contractors',
    'labor',
  ],
  loiter3: [
    'doctors',
    'sexworkers',
    'visitors',
    'staff',
    'corps',
    'security',
    'gang4',
    'labor',
  ],
  loiter4: [
    'doctors',
    'sexworkers',
    'visitors',
    'corps',
    'security',
    'gang4',
    'labor',
  ],
  lounge: [
    'doctors',
    'sexworkers',
    'visitors',
    'staff',
    'church',
    'corps',
    'contractors',
    'labor',
  ],
  worker1: ['labor', 'gang1', 'gang3', 'gang4', 'contractors'],
  worker2: ['labor', 'gang2', 'gang4', 'contractors'],
  boss: ['corps', 'gang2', 'gang1', 'gang3', 'contractors'],
  assistant: ['gang2', 'gang1', 'gang3', 'contractors', 'staff', 'doctors'],
  aid: ['doctors', 'staff', 'labor', 'church', 'visitors', 'security'],
  guest: ['labor', 'church', 'visitors', 'contractors', 'sexworkers'],
  guest2: ['visitors', 'church', 'doctors'],
  vipguest: ['church', 'visitors', 'contractors', 'sexworkers', 'doctors'],
  authority: ['corps', 'church'],
  servants2: [
    'staff',
    'security',
    'gang2',
    'gang4',
    'church',
    'sexworkers',
    'labor',
  ],
  servants1: ['staff', 'gang1', 'gang2', 'gang3', 'gang4', 'church', 'labor'],
  employee: ['staff', 'gang1', 'gang3'],
  gang: ['gang1', 'gang2', 'gang3', 'gang4'],
}
export const RoomsInitFallbacks = {
  stations: {
    admin1_passer: '',
    security_passer: '',
    reception_unplaced: '',
    grounds_unplaced: '',
  },
}
