const defaults = {
  onScreen: false,
  focus: false,
  stationKeys: [],
}
export default {
  security: {
    matrix: { x: 2, y: 5 },
    name: 'security',
    clearance: 3,
    wards: { prisoner1: '', prisoner2: '', prisoner3: '', prisoner4: '' },
    props: ['phone', 'locker'],
    actors: {
      phone: {
        id: '',
        name: 'phone',
        inventory: [],
        actions: ['use'],
        watcher: 'desk',
      },
      locker: {
        id: '',
        name: 'locker',
        inventory: [
          'ring',
          'coingold',
          'earrings',
          'silver',
          'cape',
          'magicc5',
        ],
        actions: ['use', 'open'],
        watcher: 'desk',
      },
    },
    ...defaults,
  },
  baggage: {
    matrix: { x: 0, y: 4 },
    name: 'baggage',
    clearance: 1,
    swaps: {
      worker1: ['worker2', ''],
      guard: ['patrol', ''],
    },
    actors: {
      luggage_1: {
        id: '',
        name: 'luggage_1',
        inventory: [
          'ring',
          'coingold',
          'earrings',
          'tomato',
          'mushroom03',
          'orange',
        ],
        watcher: 'browse',
        actions: ['open'],
      },
      luggage_2: {
        id: '',
        name: 'luggage_2',
        inventory: [
          'ring',
          'coingold',
          'earrings',
          'mushroom02',
          'banana',
          'vial01',
        ],
        watcher: 'guard',
        actions: ['open'],
      },
    },
    ...defaults,
  },
  viplobby: {
    matrix: { x: 1, y: 5 },
    name: 'viplobby',
    clearance: 2,
    swaps: {
      boss: ['assistant', ''],
      host: ['monitor', ''],
    },
    actors: {},
    ...defaults,
  },
  entrance: {
    matrix: { x: 0, y: 5 },
    name: 'entrance',
    clearance: 0,
    actors: {},
    ...defaults,
  },
  recroom: {
    matrix: { x: 3, y: 3 },
    name: 'recroom',
    clearance: 1,
    actors: {},
    ...defaults,
  },
  chapel: {
    matrix: { x: 3, y: 2 },
    name: 'chapel',
    clearance: 1,
    actors: {},
    ...defaults,
  },
  inn1: {
    matrix: { x: 4, y: 2 },
    name: 'inn1',
    clearance: 1,
    actors: {},
    ...defaults,
  },
  pubgrill: {
    matrix: { x: 4, y: 3 },
    name: 'pubgrill',
    clearance: 1,
    actors: {},
    ...defaults,
  },
  maintenance: {
    matrix: { x: 4, y: 1 },
    name: 'maintenance',
    clearance: 2,
    actors: {},
    ...defaults,
  },
  lobby: {
    matrix: { x: 2, y: 3 },
    name: 'lobby',
    clearance: 1,
    actors: {},
    ...defaults,
  },
  storage: {
    matrix: { x: 3, y: 1 },
    name: 'storage',
    clearance: 1,
    actors: {},
    ...defaults,
  },
  commonsint: {
    matrix: { x: 2, y: 2 },
    name: 'commonsint',
    clearance: 1,
    actors: {},
    ...defaults,
  },
  commonsext: {
    matrix: { x: 2, y: 1 },
    name: 'commonsext',
    clearance: 1,
    actors: {},
    ...defaults,
  },
  warehouse: {
    matrix: { x: 1, y: 1 },
    name: 'warehouse',
    clearance: 2,
    actors: {},
    ...defaults,
  },
  lockers: {
    matrix: { x: 1, y: 2 },
    name: 'lockers',
    clearance: 1,
    actors: {},
    ...defaults,
  },
  unloading: {
    matrix: { x: 0, y: 1 },
    name: 'unloading',
    clearance: 2,
    actors: {},
    ...defaults,
  },
  alley5: {
    matrix: { x: 4, y: 0 },
    name: 'alley5',
    clearance: 2,
    actors: {},
    ...defaults,
  },
  alley4: {
    matrix: { x: 3, y: 0 },
    name: 'alley4',
    clearance: 2,
    actors: {},
    ...defaults,
  },
  alley3: {
    matrix: { x: 2, y: 0 },
    name: 'alley3',
    clearance: 1,
    actors: {},
    ...defaults,
  },
  alley2: {
    matrix: { x: 1, y: 0 },
    name: 'alley2',
    clearance: 1,
    actors: {},
    ...defaults,
  },
  alley1: {
    matrix: { x: 0, y: 0 },
    name: 'alley1',
    clearance: 2,
    actors: {},
    ...defaults,
  },
  loading: {
    matrix: { x: 0, y: 2 },
    name: 'loading',
    clearance: 2,
    actors: {},
    ...defaults,
  },
  admin1: {
    matrix: { x: 2, y: 4 },
    name: 'admin1',
    clearance: 2,
    props: ['phone', 'locker'],
    actors: {
      phone: {
        id: '',
        name: 'phone',
        inventory: [],
        actions: ['use'],
        watcher: 'desk',
      },
      locker: {
        id: '',
        name: 'locker',
        inventory: [
          'ring',
          'coingold',
          'earrings',
          'avacado',
          'berry02',
          'shrimp02',
        ],
        actions: ['use', 'open'],
        watcher: 'desk',
      },
    },
    ...defaults,
  },
  customs: {
    matrix: { x: 1, y: 3 },
    name: 'customs',
    clearance: 0,
    props: ['phone', 'locker', 'drawer'],
    actors: {
      drawer: {
        id: '',
        name: 'desks',
        inventory: [
          'ring',
          'coingold',
          'earrings',
          'deskbook01',
          'globegold',
          'fish02',
        ],
        actions: ['open'],
        watcher: 'desk',
      },
      phone: {
        id: '',
        name: 'phone',
        inventory: [],
        actions: ['use'],
        watcher: 'desk',
      },
      locker: {
        id: '',
        name: 'locker',
        inventory: [
          'ring',
          'coingold',
          'earrings',
          'silver',
          'mushroom01',
          'potion',
        ],
        actions: ['use', 'open'],
        watcher: 'desk',
      },
      vase3: {
        id: '',
        name: 'vase3',
        inventory: [
          'ring',
          'coingold',
          'earrings',
          'steak02',
          'leaf03',
          'daisy',
          'mushroom02',
        ],
        actions: ['open'],
        watcher: 'patrol',
      },
    },
    ...defaults,
  },
  reception: {
    matrix: { x: 1, y: 4 },
    name: 'reception',
    clearance: 0,
    props: ['drawer', 'computer', 'phone'],
    actors: {
      drawer: {
        id: '',
        name: 'drawer',
        inventory: [
          'ring',
          'coingold',
          'earrings',
          'cheese',
          'shrimp01',
          'drumstick01',
        ],
        actions: ['open'],
        watcher: 'desk',
      },
      computer: {
        id: '',
        name: 'computer',
        inventory: [],
        actions: ['use'],
        watcher: 'desk',
      },
      phone: {
        id: '',
        name: 'phone',
        inventory: [],
        actions: ['use'],
        watcher: 'desk',
      },
      vase: {
        id: '',
        name: 'vase',
        inventory: ['ring', 'coingold', 'earrings', 'pillow', 'book', 'tomato'],
        actions: ['open'],
        watcher: 'loiter2',
      },
      vase2: {
        id: '',
        name: 'vase2',
        inventory: [
          'ring',
          'coingold',
          'earrings',
          'steak01',
          'leaf03',
          'daisy',
          'mushroom03',
        ],
        actions: ['open'],
        watcher: 'patrol',
      },
    },
    ...defaults,
  },
  grounds: {
    matrix: { x: 0, y: 4 },
    name: 'grounds',
    clearance: 0,
    props: ['phone', 'drawer'],
    actors: {
      player_luggage: {
        id: '',
        name: 'player_luggage',
        inventory: [
          'ring',
          'coingold',
          'earrings',
          'berry01',
          'feather01',
          'magica1',
          'orange',
        ],
        watcher: 'worker2',
        actions: ['open'],
      },
      other_luggage: {
        id: '',
        name: 'other_luggage',
        inventory: [
          'ring',
          'coingold',
          'earrings',
          'eyeball03',
          'feather02',
          'magicb1',
          'mushroom02',
        ],
        watcher: 'worker2',
        actions: ['open'],
      },
      phone: {
        id: '',
        name: 'phone',
        inventory: [],
        watcher: 'loiter1',
        actions: ['use'],
      },
      drawer: {
        id: '',
        name: 'drawer',
        inventory: ['ring', 'coingold', 'earrings', 'book'],
        watcher: 'loiter1',
        actions: ['open'],
      },
      cargo: {
        id: '',
        name: 'cargo',
        inventory: [
          'ring',
          'coingold',
          'earrings',
          'magica1',
          'magica4',
          'magicb3',
        ],
        watcher: 'guard',
        actions: ['open'],
      },
    },
    ...defaults,
  },
  dorms: {
    matrix: { x: 4, y: 5 },
    name: 'dorms',
    clearance: 1,
    actors: {},
    ...defaults,
  },
  gym: {
    matrix: { x: 3, y: 4 },
    name: 'gym',
    clearance: 1,
    actors: {},
    ...defaults,
  },
  store: {
    matrix: { x: 4, y: 4 },
    name: 'store',
    clearance: 1,
    actors: {},
    ...defaults,
  },
  infirmary: {
    matrix: { x: 3, y: 5 },
    name: 'infirmary',
    clearance: 2,
    props: ['drawer', 'computer', 'phone'],
    wards: { patient1: '', patient2: '', patient3: '', patient4: '' },
    actors: {
      drawer: {
        id: '',
        name: 'drawer',
        inventory: [
          'ring',
          'coingold',
          'earrings',
          'vial02',
          'banana',
          'vial01',
        ],
        actions: ['open'],
        watcher: 'assistant',
      },
      computer: {
        id: '',
        name: 'computer',
        inventory: [],
        actions: ['use'],
        watcher: 'assistant',
      },
      phone: {
        id: '',
        name: 'phone',
        inventory: [],
        watcher: 'assistant',
        actions: ['use'],
      },
    },
    ...defaults,
  },
}
